export default {
    questionMark: require('./questionMark.png').default,
    iPhone13ProMax1_Ellipse2: require('./iPhone13ProMax1_Ellipse2.png').default,
    iPhone13ProMax1_Ellipse4: require('./iPhone13ProMax1_Ellipse4.png').default,
    Volunteer_image2: require('./Volunteer_image2.png').default,
    Volunteer_Rectangle1: require('./Volunteer_Rectangle1.png').default,
    Refugee_Rectangle5: require('./Refugee_Rectangle5.png').default,
    Refugee_Rectangle4: require('./Refugee_Rectangle4.png').default,
    Volunteer_image6: require('./Volunteer_image6.png').default,
    Volunteer_image7: require('./Volunteer_image7.png').default,
    Refugee_inprogressicon: require('./Refugee_inprogressicon.png').default,
    Volunteer_Rectangle3: require('./Volunteer_Rectangle3.png').default,
    Refugee_createdicon: require('./Refugee_createdicon.png').default,
    Refugee_pasticon: require('./Refugee_pasticon.png').default,
    Volunteer_image8: require('./Volunteer_image8.png').default,
    Volunteer_image9: require('./Volunteer_image9.png').default,
    Volunteer_completedicon: require('./Volunteer_completedicon.png').default,
    Volunteer_image17: require('./Volunteer_image17.png').default,
}